FROM nginxdemos/hello

# Set environment variables

ENV NGINX_ENVSUBST_TEMPLATE_DIR=/usr/share/nginx/html
ENV NGINX_ENVSUBST_OUTPUT_DIR=/usr/share/nginx/html

# Copy Nginx configuration files

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html.template /usr/share/nginx/html/index.html.template

