environments:
  dev:
    values:
      - dev.values.yaml
  stg:
    values:
      - stg.values.yaml

---
releases:
  - name: hello
    namespace: default
    chart: ./hello
    values:
      - values.yaml.gotmpl
