replicaCount: 2

image:
  repository: n5challengehelloacr1.azurecr.io/challenge/hellochallenge
  tag: latest

service:
  type: LoadBalancer
  port: 80

env:
  stage: stg

azureVaultSecret: ref+azurekeyvault://hello-keyvault/demo-secret
